name: C/C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies for each OS
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install make mingw

      # Step 3: Build the project (Makefile should exist in your repository)
      - name: Build with Make
        run: make

      # Step 4: Run tests (optional, assuming Makefile has a test target)
      - name: Run tests
        run: make test

      # Step 5: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binaries-${{ runner.os }}
          path: ./bin/
