name: Publish to WinGet
on:
  release:
    types: [published, released]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: DarthDemono.PingDD
          token: ${{ secrets.WINGET_TOKEN }}
