name: Publish to WinGet

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: DarthDemono.PingDD # your winget PackageIdentifier
          token: ${{ secrets.WINGET_TOKEN }} # classic PAT with public_repo
          # optional but useful:
          # installers-regex: '\.exe$'            # if your release has multiple assets
          # max-versions-to-keep: 5
